### ISSUE TITLE
instamojo payment successful detect

### ISSUE THREAD

**Issue by SunilThombare** [aattri90/Parkit#1]
Hello,
I found your code on github regarding payment through instamojo.
I have a question:
How can I detect that the payment is successful and activate a code after successful payment. I am stuck in my code.

Please help.

Sunil
9423009650

**Comment by aattri90** [comment]
Hi Sunil,
In Payment class, there are two methods onSuccess() and onFailure() which are invoked on the basis of transaction success. So you can use these methods to implement any further functionality.

**Comment by SunilThombare** [comment]
Thanks a lot

**Comment by SunilThombare** [comment]
Thanks a lot

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
